### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by kiwiandroiddev** [inorichi/conductor-support-preference#2]
Hi, are you considering migrating this to androidx? It's having a duplicate class build error currently when the host app depends on androidx libraries. I can submit a PR with this if needed.
Thanks

**Comment by inorichi** [comment]
Sure, feel free to submit a PR.

**Comment by inorichi** [comment]
I've updated the library with AndroidX support.

If you were using `<item name="preferenceTheme">@style/PreferenceThemeOverlay.Material</item>` as explained in the readme, you'll have to remove it. They now provide a default theme that finally works well with every API (as far as I can tell) so I won't ship an updated theme anymore.
